core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
]

hunt/urls.py
from django.urls import path
from . import views

app_name = 'hunt'

urlpatterns = [
    path('hunt/', views.hunt, name='hunt'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('gen_data/', views.gen_data, name='gen_data'),
]

treasure_hunt/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('', include('hunt.urls', namespace='hunt')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_ROOT, document_root=settings.STATIC_ROOT)

core/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver


class TeamProfile(models.Model):
    class Meta:
        verbose_name = "Team Profile"
        verbose_name_plural = "Team Profiles"
        db_table = 'user_profile'

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    level_completed = models.IntegerField(default=0)
    start_time = models.DateTimeField(null=True)
    start_code = models.CharField(max_length=6)
    password = models.CharField(max_length=20,null=True)

    def __str__(self) -> str:
        return str(self.user.username) + " :::  Level: " + str(self.level_completed) + " | StartCode: " + str(self.start_code) + " | Password: " + str(self.password)


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        TeamProfile.objects.create(user=instance)
    instance.teamprofile.save()

core/views.py
import random
import string

from django.contrib.auth.decorators import login_required, user_passes_test
from django.db.models import Q
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.urls import reverse

ALUMNI = 0
STUDENT = 1


def validate_user(request, username, email):
    try:
        user = User.objects.get(Q(username=username) | Q(email=email))
    except User.DoesNotExist:
        user = None

    if user is not None:
        # user already exists
        return True
    else:
        return False


def gen_key():
    x = ''.join(random.choices(string.ascii_letters + string.digits, k=6))
    return x


@user_passes_test(lambda u: u.is_superuser)
def register(request):
    # user = request.user
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        batch_section = request.POST.get('batch_section')

        if validate_user(request, username, None):
            # user already exists
            msg = "User with this username or email already exists! :("
            messages.add_message(request, messages.ERROR, msg)
            return render(request, 'core_front_end/register.html', {
                'user_state': "exists",
            })
        else:
            # new user
            if password is None or password == '':
                password = gen_key()

            user = User.objects.create_user(username, None, password, first_name=batch_section)
            user.save()

            user.teamprofile.start_code = gen_key()
            user.teamprofile.password = password
            user.save()

            msg = "User added successfully"
            messages.add_message(request, messages.SUCCESS, msg)
            return redirect('core:register')

    else:
        return render(request, 'core_front_end/register.html')


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        print(user)

        if user is not None:
            login(request, user)
            messages.add_message(request, messages.SUCCESS, 'Welcome!')
            return redirect('hunt:hunt')

        else:
            messages.add_message(request, messages.ERROR, 'Invalid credentials')
            return render(request, 'core_front_end/login.html', {
                'view': 'login',
            })
    else:
        return render(request, 'core_front_end/login.html', {
            'view': 'login',
        })


@login_required
def logout_user(request):
    logout(request)
    msg = "Hope to see you soon! :)"
    messages.add_message(request, messages.INFO, msg)
    return redirect('core:login_user')


def home(request):
    if not request.user.is_authenticated:
        return redirect('core:login_user')
    return redirect('hunt:hunt')

core/templates/core_front_end/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    {% include 'core_front_end/load_css.html' %}
    <link type="text/css" rel="stylesheet" href="{% static 'css/toastr.min.css' %}" media="screen,projection"/>
    <!--JS -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/toastr.min.js' %}"></script>
</head>

<body>

<!-- Navbar -->
{% include 'core_front_end/navbar.html' %}

<div class="row">
    <div class="col s12 m4 offset-m4">
        {% if messages %}
            {% include 'core_front_end/toast_messages.html' %}
        {% endif %}
    </div>
</div>
</body>
</html>

core/templates/core_front_end/load_css.html
{% load static %}

<!--Let browser know website is optimized for mobile-->
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>

<!--Import Google Icon Font-->
<link href='https://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<!--Import materialize.css-->
<link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}" media="screen,projection"/>
<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}" media="screen,projection"/>

core/templates/core_front_end/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    {% include 'core_front_end/load_css.html' %}
    <link type="text/css" rel="stylesheet" href="{% static 'css/toastr.min.css' %}" media="screen,projection"/>
    <!--JS -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/toastr.min.js' %}"></script>
</head>

<body>

<!-- Navbar -->
{% include 'core_front_end/navbar.html'%}

<div class="row">
    
    <div class="col s12 m4 offset-m4">
        {% if messages %}
            {% include 'core_front_end/toast_messages.html' %}
        {% endif %}

        <div class="">
            <br><br>
        </div>

        <div class="card">
            <div class="card-action green lighten-1 white-text">
                <h4>
                    <center>
                        Welcome to BUET CSE Fest 2022: Treasure Hunt
                    </center>
                </h4>
            </div>

            <form class="" action="{% url 'core:login_user' %}" method="post">
                {% csrf_token %}
                <div class="card-content">
                    <div class="row">
                        <div class="input-field">
                            <i class="material-icons prefix">account_circle</i>
                            <input id="username" name="username" type="text" class="validate" required>
                            <label for="username">Team Name</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field">
                            <i class="material-icons prefix">lock</i>
                            <input id="password" name="password" type="password" class="validate" required>
                            <label for="password">Password</label>
                        </div>
                    </div>
                </div>
                <div class="card-action">
                    <button class="btn green waves-effect waves-light" type="submit" style="margin-left: 90px">
                        Log In
                        <i class="material-icons right">send</i>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
</body>
</html>

core/templates/core_front_end/navbar.html
{% load static %}

<div class="navbar-fixed">
    <nav class="green darken-2">
        <div class="nav-wrapper">
            <a href="{% url 'core:home' %}" class="left brand-logo">
                <img class="navbar-fixed" src="{% static 'image/logo.png' %}" />
            </a>
            <ul class="right show-on-medium-and-down">
                <li>
                    <a href="{% url 'hunt:leaderboard' %}">Leaderboard</a>
                </li>
                {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'core:logout_user' %}">Log Out</a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'core:login_user' %}">Log In</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>

core/templates/core_front_end/register.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    {% include 'core_front_end/load_css.html' %}
    <link type="text/css" rel="stylesheet" href="{% static 'css/toastr.min.css' %}" media="screen,projection"/>
    <!--JS -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/toastr.min.js' %}"></script>
</head>

<body>

<!-- Navbar -->
{% include 'core_front_end/navbar.html' %}

<div class="row">
    <div class="col s12 m4 offset-m4">
        {% if messages %}
            {% include 'core_front_end/toast_messages.html' %}
        {% endif %}
        <div class="card">
            <div class="card-action green lighten-1 white-text"><h4>Register Team Here</h4></div>
            <form class="" action="{% url 'core:register' %}" method="post">
                {% csrf_token %}
                <div class="card-content">
                    <div class="row">
                        <div class="input-field">
                            <i class="material-icons prefix">account_circle</i>
                            <input id="username" name="username" type="text" class="validate" required>
                            <label for="username">Team's Username</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field">
                            <i class="material-icons prefix">info</i>
                            <input id="batch_section" name="batch_section" type="text" class="validate" required>
                            <label for="batch_section">Team's Batch & Section (Eg. 18B)</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field">
                            <i class="material-icons prefix">lock</i>
                            <input id="password" name="password" type="password" class="validate">
                            <label for="password">Password</label>
                        </div>
                    </div>
                </div>
                <div class="card-action">
                    <button class="btn waves-effect waves-light" type="submit" style="margin-left: 90px">
                        Add
                        <i class="material-icons right">send</i>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('select').formSelect();
    });
</script>
</body>
</html>

core/templates/core_front_end/toast_messages.html
<script>
    {% for message in messages %}
        toastr.options.showMethod = 'slideDown';
        toastr.options.hideMethod = 'slideUp';
        toastr.options.progressBar = true;
        {% if message.tags == 'error' %}
            toastr.error( '{{ message }}' );
        {% elif message.tags == 'success'%}
            toastr.success( '{{ message }}' );
        {% elif message.tags == 'info'%}
            toastr.info( '{{ message }}' );
        {% endif %}
    {% endfor %}
</script>